import { Timestamp, FieldValue } from 'firebase/firestore';

export interface Feeding {
  id: string;
  timestamp: Timestamp;
  dateLocal: string;
  hourLocal: number;
  feederUid: string;
  feederName: string;
  method: 'nfc' | 'manual';
  createdAt: Timestamp;
}

// Passed to addDoc — id is generated by Firestore, timestamp is client Date, createdAt is server sentinel
export type NewFeeding = Omit<Feeding, 'id' | 'createdAt' | 'timestamp'> & {
  timestamp: Date;
  createdAt: FieldValue;
};
