import { Timestamp, FieldValue } from 'firebase/firestore';

export interface Feeding {
  id: string;
  timestamp: Timestamp;
  dateLocal: string;
  hourLocal: number;
  feederUid: string;
  feederName: string;
  method: 'nfc' | 'manual';
  createdAt: Timestamp;
}

// Passed to addDoc — id is generated by Firestore, timestamp is client Date, createdAt is server sentinel
export type NewFeeding = Omit<Feeding, 'id' | 'createdAt' | 'timestamp'> & {
  timestamp: Date;
  createdAt: FieldValue;
};

export type MealSlotId = 'morning' | 'midday' | 'afternoon' | 'night';

export interface MealSlot {
  id: MealSlotId;
  name: string;
  label: string;
  startHour: number;
  endHour: number;
  bg: string;
}

export type SlotStatus = 'not-yet' | 'pending' | 'given' | 'missed' | 'skipped';

export interface Skip {
  id: string;
  date: string;
  mealSlotId: MealSlotId;
  skippedBy: string;
  skippedByName: string;
  skippedAt: Timestamp;
}
